image: pulumi/pulumi-python:latest

stages:
    - pulumi

variables:
  PULUMI_STACK_NAME: [[ .PulumiStackName ]]
  PULUMI_WORKING_DIRECTORY: [[ .WorkingDirectory ]]

only:
  changes:
    - [[ .PathFilter ]]

default:
  before_script:
    - |
      pushd ${PULUMI_WORKING_DIRECTORY}
      # Check if should use venv
      PULUMI_VENV=$(cat Pulumi.yaml | grep "virtualenv:" | cut -d':' -f2)
      if [ -z ${PULUMI_VENV} ]; then
          pip3 install -r requirements.txt
      else
          python3 -m venv ${PULUMI_VENV}
          ${PULUMI_VENV}/bin/python -m pip install --upgrade pip setuptools wheel
          ${PULUMI_VENV}/bin/python -m pip install -r requirements.txt
      fi
      popd

# Having problems with environment variables?
# Uncomment the following job to see all env vars
# exported in your GitLab Runner.
# environment:
#   stage: pulumi
#   script:
#     - export

preview:
  stage: pulumi
  script:
    - pulumi preview --cwd ${PULUMI_WORKING_DIRECTORY} -s ${PULUMI_STACK_NAME}
  only:
    - merge_requests

update:
  stage: pulumi
  script:
    - pulumi up --yes --cwd ${PULUMI_WORKING_DIRECTORY} -s ${PULUMI_STACK_NAME}
  only:
    refs:
      - main
