image: pulumi/pulumi-python:latest

definitions:
  steps:
    - step:
        name: Restore Python dependencies
        script:
          - &deps |
            export PULUMI_STACK_NAME=[[ .PulumiStackName ]]
            export PULUMI_WORKING_DIRECTORY=[[ .WorkingDirectory ]]
            # Change to the working directory for the Pulumi app and restore dependencies.
            pushd ${PULUMI_WORKING_DIRECTORY}
            # Check if should use venv
            PULUMI_VENV=$(cat Pulumi.yaml | grep "virtualenv:" | cut -d':' -f2)
            if [ -z ${PULUMI_VENV} ]; then
                pip3 install -r requirements.txt
            else
                python3 -m venv ${PULUMI_VENV}
                ${PULUMI_VENV}/bin/python -m pip install --upgrade pip setuptools wheel
                ${PULUMI_VENV}/bin/python -m pip install -r requirements.txt
            fi
            popd

pipelines:
  pull-requests:
    '**':
      - step:
          name: Preview update to infrastructure
          script:
            - *deps
            - pulumi preview --cwd ${PULUMI_WORKING_DIRECTORY} -s ${PULUMI_STACK_NAME}

  branches:
    main:
      - step:
          name: Update infrastructure
          # Using the deployment keyword will ensure that only one pipeline is executing for
          # the deployment environment at any given time.
          #
          # Valid values are: test, staging, or production.
          # Add new environments in your repository's Deployment Settings page.
          # Learn more: https://support.atlassian.com/bitbucket-cloud/docs/set-up-and-monitor-bitbucket-deployments/
          deployment: test
          script:
            - *deps
            - pulumi up --yes --cwd ${PULUMI_WORKING_DIRECTORY} -s ${PULUMI_STACK_NAME}
