name: Preview or update Pulumi app [[ .PulumiStackName ]]
on:
  push:
    branches:
      - master
    paths:
      - [[ .PathFilter ]]
  pull_request:
    branches:
      - master
    paths:
      - [[ .PathFilter ]]

# These are the environment variables that jobs in the workflow have access to.
# By defining them here, all jobs/steps will have access to these variables.
env:
  # IMPORTANT! You must map the env vars for your cloud provider here even though you add them as secrets
  # to this repository.
  # See the setup page for cloud providers here: https://www.pulumi.com/docs/intro/cloud-providers/.
  # For example, if you are using AWS, then you should add the following:
  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_STACK_NAME: [[ .PulumiStackName ]]
  PULUMI_WORKING_DIRECTORY: [[ .WorkingDirectory ]]

jobs:
  pulumi:
    name: Pulumi
    runs-on: ubuntu-latest
    steps:

      # Turnstyle is used to prevent multiple push jobs from running at the same time. We
      # limit it to push jobs to allow PR jobs to run concurrently.
      - name: Turnstyle
        if: ${{ github.event_name == 'push' }}
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.x
    
      - run: |
          # Check if should use venv
          PULUMI_VENV=$(cat Pulumi.yaml | grep "virtualenv:" | cut -d':' -f2)
          if [ -z ${PULUMI_VENV} ]; then
              pip3 install -r requirements.txt
          else
              python3 -m venv ${PULUMI_VENV}
              ${PULUMI_VENV}/bin/python -m pip install --upgrade pip setuptools wheel
              ${PULUMI_VENV}/bin/python -m pip install -r requirements.txt
          fi
        name: Restore Python dependencies
        working-directory: ${{ env.PULUMI_WORKING_DIRECTORY }}

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1

      - name: PR previews
        run: pulumi preview -s $PULUMI_STACK_NAME --cwd ${PULUMI_WORKING_DIRECTORY}
        if: ${{ github.event_name == 'pull_request' }}

      - name: Apply infrastructure update
        run: pulumi update --yes -s $PULUMI_STACK_NAME --cwd ${PULUMI_WORKING_DIRECTORY}
        if: ${{ github.event_name == 'push' }}
