name: Preview or update Pulumi app {{ .PulumiStackName }}
on:
  push:
    branches:
      - master
    {{ .PathFilter }}
  pull_request:
    branches:
      - master
    {{ .PathFilter }}

# These are the environment variables that jobs in the workflow have access to.
# By defining them here, all jobs/steps will have access to these variables.
env:
  # IMPORTANT! You must map the env vars for your cloud provider here even though you add them as secrets
  # to this repository.
  # See the setup page for cloud providers here: https://www.pulumi.com/docs/intro/cloud-providers/.
  # For example, if you are using AWS, then you should add the following:
  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_STACK_NAME: {{ .PulumiStackName }}
  PULUMI_WORKING_DIRECTORY: {{ .WorkingDirectory }}

jobs:
  pulumi:
    name: Pulumi
    runs-on: ubuntu-latest
    steps:

      # Turnstyle is used to prevent multiple push jobs from running at the same time. We
      # limit it to push jobs to allow PR jobs to run concurrently.
      - name: Turnstyle
        if: ${{ github.event_name == 'push' }}
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@releases/v1

      - name: Restore npm dependencies
        run: |
          npm --prefix $PULUMI_WORKING_DIRECTORY ci
          # If you are using yarn instead with Pulumi, comment the above line and uncomment the below line.
          # yarn install --cwd $PULUMI_WORKING_DIRECTORY

      - name: PR previews
        run: pulumi preview -s $PULUMI_STACK_NAME --cwd $PULUMI_WORKING_DIRECTORY
        if: ${{ github.event_name == 'pull_request' }}

      - name: Apply infrastructure update
        run: pulumi update --yes -s $PULUMI_STACK_NAME --cwd $PULUMI_WORKING_DIRECTORY
        if: ${{ github.event_name == 'push' }}
