trigger:
    batch: true
    branches:
      include:
      - main
    paths:
      include:
      - [[ .PathFilter ]]

pr:
  branches:
    include:
    # Run PR builds that target main.
    - main
  paths:
    include:
    - [[ .PathFilter ]]


pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  pulumiStackName: [[ .PulumiStackName ]]
  pulumiWorkingDirectory: [[ .WorkingDirectory ]]

jobs:
- job: infrastructure
  steps:
  - task: NuGetToolInstaller@1

  - task: Pulumi@1
    condition: eq(variables['Build.Reason'], 'PullRequest')
    inputs:
      # To use an Azure Service Connection, un-comment the following line.
      # azureSubscription: ''
      command: 'preview'
      stack: '$(pulumiStackName)'
      args: '--cwd $(pulumiWorkingDirectory)'

  - task: Pulumi@1
    condition: or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'BatchedCI'))
    inputs:
      # To use an Azure Service Connection, un-comment the following line.
      # azureSubscription: ''
      command: 'up'
      stack: '$(pulumiStackName)'
      args: '--yes --cwd $(pulumiWorkingDirectory)'
